<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZrso5av\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZrso5av/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZrso5av.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZrso5av\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZrso5av\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zrso5av',
    'container.build_id' => '53a14e2c',
    'container.build_time' => 1535545237,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZrso5av');
